### ISSUE TITLE
sudo make -f makefile.unix # Headless magnet error

### ISSUE THREAD

**Issue by himawanwi** [magnetwork/magnet#1]
i follow the instruction:
BUILD LINUX
git clone https://github.com/magnetwork/magnet.git MAGNET
cd MAGNET/src/leveldb
make libleveldb.a libmemenv.a
(check permissions if any error)
cd ..

when i do this :
sudo make -f makefile.unix # Headless magnet

this error happen:

/bin/sh ../share/genbuild.sh obj/build.h
Building Secp256k1 ...
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
/bin/sh: 1: ./configure: not found
make[1]: Entering directory `/home/mypool/MAGNET/src/secp256k1'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/home/mypool/MAGNET/src/secp256k1'
g++ -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wunused-function -Wunused-variable -fpermissive -Wconversion-null -g -DBOOST_SPIRIT_THREADSAFE -I/home/mypool/MAGNET/src -I/home/mypool/MAGNET/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -DENABLE_WALLET -I/home/mypool/MAGNET/src/secp256k1/include -I/home/mypool/MAGNET/src/leveldb/include -I/home/mypool/MAGNET/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -o magnetd obj/alert.o obj/allocators.o obj/version.o obj/support/cleanse.o obj/checkpoints.o obj/netbase.o obj/addrman.o obj/base58.o obj/crypter.o obj/key.o obj/pubkey.o obj/ecwrapper.o obj/init.o obj/bitcoind.o obj/keystore.o obj/core.o obj/main.o obj/net.o obj/protocol.o obj/rpcclient.o obj/rpcprotocol.o obj/rpcserver.o obj/rpcmisc.o obj/rpcnet.o obj/rpcblockchain.o obj/rpcrawtransaction.o obj/rpcsmessage.o obj/script.o obj/scrypt.o obj/sync.o obj/txmempool.o obj/util.o obj/hash.o obj/noui.o obj/kernel.o obj/pbkdf2.o obj/chainparams.o obj/stealth.o obj/activemasternode.o obj/darksend.o obj/darksend-relay.o obj/instantx.o obj/masternodeconfig.o obj/masternodeman.o obj/masternode.o obj/masternode-payments.o obj/rpcdarksend.o obj/spork.o obj/crypto/hmac_sha256.o obj/crypto/hmac_sha512.o obj/crypto/ripemd160.o obj/crypto/sha1.o obj/crypto/sha256.o obj/crypto/sha512.o obj/smessage.o obj/cubehash.o obj/luffa.o obj/aes_helper.o obj/echo.o obj/shavite.o obj/simd.o obj/blake.o obj/bmw.o obj/groestl.o obj/jh.o obj/keccak.o obj/skein.o obj/db.o obj/miner.o obj/rpcdump.o obj/rpcmining.o obj/rpcwallet.o obj/wallet.o obj/walletdb.o obj/txdb-leveldb.o secp256k1/src/libsecp256k1_la-secp256k1.o -Wl,-z,relro -Wl,-z,now   -Wl,-Bdynamic -Wl,-Bdynamic -l boost_system -l boost_filesystem -l boost_program_options -l boost_thread -l db_cxx -l ssl -l gmp -l crypto -l miniupnpc -Wl,-Bdynamic -l z -l dl -l pthread /home/mypool/MAGNET/src/leveldb/libleveldb.a /home/mypool/MAGNET/src/leveldb/libmemenv.a
g++: error: secp256k1/src/libsecp256k1_la-secp256k1.o: No such file or directory
make: *** [magnetd] Error 1

please help

**Comment by FredericRezeau** [comment]
Hi, looks like your system does not have automake/autoconf installed?
sudo apt-get install autotools-dev
sudo apt-get install autoconf

**Comment by himawanwi** [comment]
mypool@pool:~$ sudo apt-get install autotools-dev
[sudo] password for mypool:
Reading package lists... Done
Building dependency tree
Reading state information... Done
autotools-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

mypool@pool:~$ sudo apt-get install autoconf
Reading package lists... Done
Building dependency tree
Reading state information... Done
autoconf is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

mypool@pool:~/MAGNET/src$ sudo make -f makefile.unix # Headless magnet
/bin/sh ../share/genbuild.sh obj/build.h
g++ -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wunused-function -Wunused-variable -fpermissive -Wconversion-null -g -DBOOST_SPIRIT_THREADSAFE -I/home/mypool/MAGNET/src -I/home/mypool/MAGNET/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -DENABLE_WALLET -I/home/mypool/MAGNET/src/secp256k1/include -I/home/mypool/MAGNET/src/leveldb/include -I/home/mypool/MAGNET/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -o magnetd obj/alert.o obj/allocators.o obj/version.o obj/support/cleanse.o obj/checkpoints.o obj/netbase.o obj/addrman.o obj/base58.o obj/crypter.o obj/key.o obj/pubkey.o obj/ecwrapper.o obj/init.o obj/bitcoind.o obj/keystore.o obj/core.o obj/main.o obj/net.o obj/protocol.o obj/rpcclient.o obj/rpcprotocol.o obj/rpcserver.o obj/rpcmisc.o obj/rpcnet.o obj/rpcblockchain.o obj/rpcrawtransaction.o obj/rpcsmessage.o obj/script.o obj/scrypt.o obj/sync.o obj/txmempool.o obj/util.o obj/hash.o obj/noui.o obj/kernel.o obj/pbkdf2.o obj/chainparams.o obj/stealth.o obj/activemasternode.o obj/darksend.o obj/darksend-relay.o obj/instantx.o obj/masternodeconfig.o obj/masternodeman.o obj/masternode.o obj/masternode-payments.o obj/rpcdarksend.o obj/spork.o obj/crypto/hmac_sha256.o obj/crypto/hmac_sha512.o obj/crypto/ripemd160.o obj/crypto/sha1.o obj/crypto/sha256.o obj/crypto/sha512.o obj/smessage.o obj/cubehash.o obj/luffa.o obj/aes_helper.o obj/echo.o obj/shavite.o obj/simd.o obj/blake.o obj/bmw.o obj/groestl.o obj/jh.o obj/keccak.o obj/skein.o obj/db.o obj/miner.o obj/rpcdump.o obj/rpcmining.o obj/rpcwallet.o obj/wallet.o obj/walletdb.o obj/txdb-leveldb.o secp256k1/src/libsecp256k1_la-secp256k1.o -Wl,-z,relro -Wl,-z,now   -Wl,-Bdynamic -Wl,-Bdynamic -l boost_system -l boost_filesystem -l boost_program_options -l boost_thread -l db_cxx -l ssl -l gmp -l crypto -l miniupnpc -Wl,-Bdynamic -l z -l dl -l pthread /home/mypool/MAGNET/src/leveldb/libleveldb.a /home/mypool/MAGNET/src/leveldb/libmemenv.a
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
make: *** [magnetd] Error 1

**Comment by FredericRezeau** [comment]
To install gmp: sudo apt-get install libgmp3-dev

**Comment by himawanwi** [comment]
sory, i am late to update.
i have other case : using this pool setup
https://blockgen.net/setup-your-own-mining-pool/
i success configure litecoin, but why reject hash for x11 magnet and pool restared after few minute

**Comment by himawanwi** [comment]
/home/mypool/unomp/node_modules/merged-pooler/lib/blockTemplate.js:28
            [util.varIntBuffer(rpcData.votes.length)].concat(
                                            ^
TypeError: Cannot read property 'length' of undefined
    at getVoteData (/home/mypool/unomp/node_modules/merged-pooler/lib/blockTemplate.js:28:45)
    at BlockTemplate.serializeBlock (/home/mypool/unomp/node_modules/merged-pooler/lib/blockTemplate.js:108:13)
    at JobManager.processShare (/home/mypool/unomp/node_modules/merged-pooler/lib/jobManager.js:274:31)
    at null.<anonymous> (/home/mypool/unomp/node_modules/merged-pooler/lib/pool.js:630:46)
    at EventEmitter.emit (events.js:98:17)
    at handleSubmit (/home/mypool/unomp/node_modules/merged-pooler/lib/stratum.js:175:15)
    at handleMessage (/home/mypool/unomp/node_modules/merged-pooler/lib/stratum.js:88:17)
    at /home/mypool/unomp/node_modules/merged-pooler/lib/stratum.js:248:25
    at Array.forEach (native)
    at Socket.<anonymous> (/home/mypool/unomp/node_modules/merged-pooler/lib/stratum.js:234:26)
[2017-11-27 12:48:32.124] [ERROR] [default] - Master PoolSpawner Fork 0 died, spawning replacement worker...

**Comment by FredericRezeau** [comment]
https://github.com/magnetwork/magnetpool/blob/master/lib/blockTemplate.js
I am not sure about Dash specifics but this is how I modified for Magnet pool.

**Comment by himawanwi** [comment]
it work, thank you very much
