### ISSUE TITLE
Masternode Payments

### ISSUE THREAD

**Issue by raulgonve** [magnetwork/magnet#15]
6 days without receive the 100 magnet payment in masternodes, just the smaller payments

**Comment by FredericRezeau** [comment]
This issue was fixed by forked @ block 145000 (v1.3.0). 

Make sure you have updated your wallet: https://magnetwork.io/2018/01/31/hard-fork-wallet-update-guide/

Additionally this blog entry might help : https://magnetwork.io/2018/02/26/masternode-rewards-in-question/
