### ISSUE TITLE
Windows install instructions missing MinGW install

### ISSUE THREAD

**Issue by stopher** [magnetwork/magnet#2]
I follow instructions for windows install but MinGW is not installed at C:\MinGW49-32\msys\1.0. Where in the process should MinGW be installed?

**Comment by FredericRezeau** [comment]
Hi, indeed the windows compilation instruction is outdated (from the fork). The fastest way to get a compilation toolchain working for Windows is to use MXE (M cross environment) and cross-compile from Linux.
