### ISSUE TITLE
Magnet-cli command

### ISSUE THREAD

**Issue by yoburtu** [magnetwork/magnet#4]
Hello,

Can I get a magnet-cli command for use in command line and shell scripts?.

Best regards.

**Comment by FredericRezeau** [comment]
Hi yoburtu, I believe magnetd is what you are looking for (rpc daemon on command line).

**Comment by yoburtu** [comment]
Hi,

Thanks you. Now I have learned to handle the magnets command well.

Thanks you!.

Best regards.

**Comment by FredericRezeau** [comment]
You're welcome, glad to help.
