### ISSUE TITLE
Windows wallet taking up about 17% of CPU

### ISSUE THREAD

**Issue by psytek** [magnetwork/magnet#6]
![image](https://user-images.githubusercontent.com/234438/34460355-b0afbd72-edd9-11e7-9fec-5749ae205ff0.png)

**Comment by FredericRezeau** [comment]
Thanks we will be looking into this one shortly.

**Comment by psytek** [comment]
Thanks so much.  Let me know if you need any more info.

**Comment by gwestwood** [comment]
@psytek Was the wallet syncing at the time?  I only see loads of up to 12.5% (on an i7) with version 1.2.1.0 while it is syncing.

**Comment by psytek** [comment]
No, it was staking, the wallet was fully synced.

**Comment by FredericRezeau** [comment]
This was fixed in the latest release (1.3.0)
