### ISSUE TITLE
"Magnet Network" tab in wallet doesn't show active status, active (secs), last seen, or pubkey for many nodes.

### ISSUE THREAD

**Issue by educatedwarrior** [magnetwork/magnet#7]
![image](https://user-images.githubusercontent.com/4054610/34482634-3b4102a8-ef87-11e7-843d-f29da2e12e21.png)

**Comment by FredericRezeau** [comment]
Thanks, yes that specific view has issues with the refresh and this will be addressed as we move along the roadmap - the UI will be refactored to use another tech stack.

**Comment by FredericRezeau** [comment]
Alternatively in the meantime you can use this command:
(Help > Debug Window > Console Tab)
**masternodelist** 
or visit our online tool : http://magnetwork.io/checkmn/
