### ISSUE TITLE
Masternode ranking doesn't appear it's calculating correctly.

### ISSUE THREAD

**Issue by educatedwarrior** [magnetwork/magnet#9]
I'm currently running two masternodes.   I started them at the exact same time yesterday and their ranking is not in the same ball park.   

One masternode is ranked at 130 and the other is ranked at 397.   There is no way this cold be unless over 200 nodes started up within a couple seconds.  Not possible.

**Comment by the-scott-davis** [comment]
The rankings for this wallet seem to be inaccurate in general. When the Masternode list refreshes every 60 seconds or so, the entire list seems to update to random values. As a result. I do not believe it is using the masternode winners list at all.... not really sure what this display is based on to be honest. Would be great to get some clarification.

**Comment by FredericRezeau** [comment]
Hello, the ranking is based on a deterministic pseudo-random function which can be found in the code (masternode.cpp CMasternode::CalculateScore). Additionally you can check this lenghty explanation on our blog: https://magnetwork.io/2018/02/26/masternode-rewards-in-question/
